name: Repository Attributes
description: Expose various attributes of a repository available as variables
inputs:
  head:
    description: Most recent repo reference
    required: true
    default: ""
  tail:
    description: A prior repo reference to check for chnages from (empty default infers the previous tag or the initial commit)
    required: true
    default: ""
outputs:
  head:
    description: Evaluated most recent repo reference
  tail:
    description: Evaluated previous reference
  commits:
    description: List of commits (hashe and message)
  prs:
    description: List of pull requests (number and title)
  files:
    description: List of files (change summary)
  contributors:
    description: List of contributors (name and number of commits)
runs:
  using: docker
  image: Dockerfile
branding:
  icon: tag
  color: blue
